"""Add ExcersideData model

Revision ID: 33e85d301f5c
Revises: a6b6daf41a13
Create Date: 2024-05-22 03:44:56.881826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e85d301f5c'
down_revision = 'a6b6daf41a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('left_forearm_innerbody', sa.Integer(), nullable=True),
    sa.Column('left_forearm_outterbody', sa.Integer(), nullable=True),
    sa.Column('right_forearm_innerbody', sa.Integer(), nullable=True),
    sa.Column('right_forearm_outterbody', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_data')
    # ### end Alembic commands ###
